from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 991, 571))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.btn43 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn43.sizePolicy().hasHeightForWidth())
        self.btn43.setSizePolicy(sizePolicy)
        self.btn43.setObjectName("btn43")
        self.gridLayout.addWidget(self.btn43, 3, 2, 1, 1)
        self.btn24 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn24.sizePolicy().hasHeightForWidth())
        self.btn24.setSizePolicy(sizePolicy)
        self.btn24.setObjectName("btn24")
        self.gridLayout.addWidget(self.btn24, 1, 3, 1, 1)
        self.btn63 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn63.sizePolicy().hasHeightForWidth())
        self.btn63.setSizePolicy(sizePolicy)
        self.btn63.setObjectName("btn63")
        self.gridLayout.addWidget(self.btn63, 5, 2, 1, 1)
        self.btn62 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn62.sizePolicy().hasHeightForWidth())
        self.btn62.setSizePolicy(sizePolicy)
        self.btn62.setObjectName("btn62")
        self.gridLayout.addWidget(self.btn62, 5, 1, 1, 1)
        self.btn42 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn42.sizePolicy().hasHeightForWidth())
        self.btn42.setSizePolicy(sizePolicy)
        self.btn42.setObjectName("btn42")
        self.gridLayout.addWidget(self.btn42, 3, 1, 1, 1)
        self.btn64 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn64.sizePolicy().hasHeightForWidth())
        self.btn64.setSizePolicy(sizePolicy)
        self.btn64.setObjectName("btn64")
        self.gridLayout.addWidget(self.btn64, 5, 3, 1, 1)
        self.btn13 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn13.sizePolicy().hasHeightForWidth())
        self.btn13.setSizePolicy(sizePolicy)
        self.btn13.setObjectName("btn13")
        self.gridLayout.addWidget(self.btn13, 0, 2, 1, 1)
        self.btn65 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn65.sizePolicy().hasHeightForWidth())
        self.btn65.setSizePolicy(sizePolicy)
        self.btn65.setObjectName("btn65")
        self.gridLayout.addWidget(self.btn65, 5, 4, 1, 1)
        self.btn44 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn44.sizePolicy().hasHeightForWidth())
        self.btn44.setSizePolicy(sizePolicy)
        self.btn44.setObjectName("btn44")
        self.gridLayout.addWidget(self.btn44, 3, 3, 1, 1)
        self.btn34 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn34.sizePolicy().hasHeightForWidth())
        self.btn34.setSizePolicy(sizePolicy)
        self.btn34.setObjectName("btn34")
        self.gridLayout.addWidget(self.btn34, 2, 3, 1, 1)
        self.btn33 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn33.sizePolicy().hasHeightForWidth())
        self.btn33.setSizePolicy(sizePolicy)
        self.btn33.setObjectName("btn33")
        self.gridLayout.addWidget(self.btn33, 2, 2, 1, 1)
        self.btn35 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn35.sizePolicy().hasHeightForWidth())
        self.btn35.setSizePolicy(sizePolicy)
        self.btn35.setObjectName("btn35")
        self.gridLayout.addWidget(self.btn35, 2, 4, 1, 1)
        self.btn12 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn12.sizePolicy().hasHeightForWidth())
        self.btn12.setSizePolicy(sizePolicy)
        self.btn12.setObjectName("btn12")
        self.gridLayout.addWidget(self.btn12, 0, 1, 1, 1)
        self.btn25 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn25.sizePolicy().hasHeightForWidth())
        self.btn25.setSizePolicy(sizePolicy)
        self.btn25.setObjectName("btn25")
        self.gridLayout.addWidget(self.btn25, 1, 4, 1, 1)
        self.btn32 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn32.sizePolicy().hasHeightForWidth())
        self.btn32.setSizePolicy(sizePolicy)
        self.btn32.setObjectName("btn32")
        self.gridLayout.addWidget(self.btn32, 2, 1, 1, 1)
        self.btn22 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn22.sizePolicy().hasHeightForWidth())
        self.btn22.setSizePolicy(sizePolicy)
        self.btn22.setObjectName("btn22")
        self.gridLayout.addWidget(self.btn22, 1, 1, 1, 1)
        self.btn23 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn23.sizePolicy().hasHeightForWidth())
        self.btn23.setSizePolicy(sizePolicy)
        self.btn23.setObjectName("btn23")
        self.gridLayout.addWidget(self.btn23, 1, 2, 1, 1)
        self.btn41 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn41.sizePolicy().hasHeightForWidth())
        self.btn41.setSizePolicy(sizePolicy)
        self.btn41.setObjectName("btn41")
        self.gridLayout.addWidget(self.btn41, 3, 0, 1, 1)
        self.btn14 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn14.sizePolicy().hasHeightForWidth())
        self.btn14.setSizePolicy(sizePolicy)
        self.btn14.setObjectName("btn14")
        self.gridLayout.addWidget(self.btn14, 0, 3, 1, 1)
        self.btn11 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn11.sizePolicy().hasHeightForWidth())
        self.btn11.setSizePolicy(sizePolicy)
        self.btn11.setObjectName("btn11")
        self.gridLayout.addWidget(self.btn11, 0, 0, 1, 1)
        self.btn21 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn21.sizePolicy().hasHeightForWidth())
        self.btn21.setSizePolicy(sizePolicy)
        self.btn21.setObjectName("btn21")
        self.gridLayout.addWidget(self.btn21, 1, 0, 1, 1)
        self.btn45 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn45.sizePolicy().hasHeightForWidth())
        self.btn45.setSizePolicy(sizePolicy)
        self.btn45.setObjectName("btn45")
        self.gridLayout.addWidget(self.btn45, 3, 4, 1, 1)
        self.btn53 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn53.sizePolicy().hasHeightForWidth())
        self.btn53.setSizePolicy(sizePolicy)
        self.btn53.setObjectName("btn53")
        self.gridLayout.addWidget(self.btn53, 4, 2, 1, 1)
        self.btn52 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn52.sizePolicy().hasHeightForWidth())
        self.btn52.setSizePolicy(sizePolicy)
        self.btn52.setObjectName("btn52")
        self.gridLayout.addWidget(self.btn52, 4, 1, 1, 1)
        self.btn15 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn15.sizePolicy().hasHeightForWidth())
        self.btn15.setSizePolicy(sizePolicy)
        self.btn15.setObjectName("btn15")
        self.gridLayout.addWidget(self.btn15, 0, 4, 1, 1)
        self.btn61 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn61.sizePolicy().hasHeightForWidth())
        self.btn61.setSizePolicy(sizePolicy)
        self.btn61.setObjectName("btn61")
        self.gridLayout.addWidget(self.btn61, 5, 0, 1, 1)
        self.btn31 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn31.sizePolicy().hasHeightForWidth())
        self.btn31.setSizePolicy(sizePolicy)
        self.btn31.setObjectName("btn31")
        self.gridLayout.addWidget(self.btn31, 2, 0, 1, 1)
        self.btn51 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn51.sizePolicy().hasHeightForWidth())
        self.btn51.setSizePolicy(sizePolicy)
        self.btn51.setObjectName("btn51")
        self.gridLayout.addWidget(self.btn51, 4, 0, 1, 1)
        self.btn55 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn55.sizePolicy().hasHeightForWidth())
        self.btn55.setSizePolicy(sizePolicy)
        self.btn55.setObjectName("btn55")
        self.gridLayout.addWidget(self.btn55, 4, 4, 1, 1)
        self.btn54 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn54.sizePolicy().hasHeightForWidth())
        self.btn54.setSizePolicy(sizePolicy)
        self.btn54.setObjectName("btn54")
        self.gridLayout.addWidget(self.btn54, 4, 3, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(502, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_confirm_2 = QtWidgets.QPushButton(self.frame_3)
        self.btn_confirm_2.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_confirm_2.setMaximumSize(QtCore.QSize(80, 60))
        self.btn_confirm_2.setObjectName("btn_confirm_2")
        self.horizontalLayout.addWidget(self.btn_confirm_2)
        self.btn_confirm = QtWidgets.QPushButton(self.frame_3)
        self.btn_confirm.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_confirm.setMaximumSize(QtCore.QSize(80, 60))
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout.addWidget(self.btn_confirm)
        self.btn_confirm_3 = QtWidgets.QPushButton(self.frame_3)
        self.btn_confirm_3.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_confirm_3.setMaximumSize(QtCore.QSize(80, 60))
        self.btn_confirm_3.setObjectName("btn_confirm_3")
        self.horizontalLayout.addWidget(self.btn_confirm_3)
        self.horizontalLayout.setStretch(0, 15)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btn_confirm_2.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "请在下方设计实验数据记录表"))
        self.btn43.setText(_translate("MainWindow", "自定义"))
        self.btn24.setText(_translate("MainWindow", "自定义"))
        self.btn63.setText(_translate("MainWindow", "自定义"))
        self.btn62.setText(_translate("MainWindow", "自定义"))
        self.btn42.setText(_translate("MainWindow", "自定义"))
        self.btn64.setText(_translate("MainWindow", "自定义"))
        self.btn13.setText(_translate("MainWindow", "自定义"))
        self.btn65.setText(_translate("MainWindow", "自定义"))
        self.btn44.setText(_translate("MainWindow", "自定义"))
        self.btn34.setText(_translate("MainWindow", "自定义"))
        self.btn33.setText(_translate("MainWindow", "自定义"))
        self.btn35.setText(_translate("MainWindow", "自定义"))
        self.btn12.setText(_translate("MainWindow", "自定义"))
        self.btn25.setText(_translate("MainWindow", "自定义"))
        self.btn32.setText(_translate("MainWindow", "自定义"))
        self.btn22.setText(_translate("MainWindow", "自定义"))
        self.btn23.setText(_translate("MainWindow", "自定义"))
        self.btn41.setText(_translate("MainWindow", "自定义"))
        self.btn14.setText(_translate("MainWindow", "自定义"))
        self.btn11.setText(_translate("MainWindow", "自定义"))
        self.btn21.setText(_translate("MainWindow", "自定义"))
        self.btn45.setText(_translate("MainWindow", "自定义"))
        self.btn53.setText(_translate("MainWindow", "自定义"))
        self.btn52.setText(_translate("MainWindow", "自定义"))
        self.btn15.setText(_translate("MainWindow", "自定义"))
        self.btn61.setText(_translate("MainWindow", "自定义"))
        self.btn31.setText(_translate("MainWindow", "自定义"))
        self.btn51.setText(_translate("MainWindow", "自定义"))
        self.btn55.setText(_translate("MainWindow", "自定义"))
        self.btn54.setText(_translate("MainWindow", "自定义"))
        self.btn_confirm_2.setText(_translate("MainWindow", "关闭"))
        self.btn_confirm.setText(_translate("MainWindow", "确定"))
        self.btn_confirm_3.setText(_translate("MainWindow", "提交"))
